version: "3.9"

services:
  postgreschitter:
    image: postgres:latest
    container_name: postgresChitter
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1329TDEV!
    volumes:
      - ./data_sm:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - web_network

  pgadminchitter:
    image: dpage/pgadmin4:latest
    container_name: pgadminChitter
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgreschitter
    restart: unless-stopped
    networks:
      - web_network
volumes:
  data_sm:

networks:
  web_network:
    name: tamnetwork